### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by chkoar** [ines/wasabi#5]
It seems that colors do not work in Windows.
In an ipython session:
![image](https://user-images.githubusercontent.com/11897937/60871495-8cc4f900-a23b-11e9-9b20-40bc4aa04b74.png)
In a python script:
![image](https://user-images.githubusercontent.com/11897937/60871531-9e0e0580-a23b-11e9-8640-4a004333b856.png)

Also, the  following example, that is stated in the readme, does not work, at least in my Windows box.
```python
msg = Printer()
with msg.loading("Loading..."):
    # Do something here that takes longer
    time.sleep(10)
msg.good("Successfully loaded something!")
```

It should be wrapped under the `__name__ == "__main__"` like this:

```python
if __name__ == "__main__":
    msg = Printer()
    with msg.loading("Loading..."):
        # Do something here that takes longer
        time.sleep(10)
    msg.good("Successfully loaded something!")
```
Otherwise you will get a `RuntimeError`:

```
An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by BreakBB** [comment]
To which Windows console does your "in a python script" reference? Looks like the built in PyCharm "Run" environment.

I understand your problem about the colors and you're right that normal windows consoles (cmd and PowerShell) don't show colors correctly.

After some research I found a piece of code [here](https://stackoverflow.com/a/36760881/6419859) to set the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag using the `ctypes` package:

```python
import ctypes
kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
```

Maybe this could be added to [supports_ansi](https://github.com/ines/wasabi/blob/master/wasabi/util.py#L164) in some way. Since ANSI escape sequences are only supported for Windows 10 as far as I know checking `if sys.platform == "win32"` is most likely not enough before running the code snipped from above.

This is the test and some results on my machine:

```python
import ctypes
from wasabi import Printer
p = Printer()

print("Before:")
p.good("Good")
p.info("Info")
p.warn("Warn")
p.fail("Fail")

kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
p.show_color = True

print("\nAfter:")

p.good("Good")
p.info("Info")
p.warn("Warn")
p.fail("Fail")
```

Windows cmd and PowerShell:
![grafik](https://user-images.githubusercontent.com/33514570/61282847-5d266b80-a7bc-11e9-8674-4e2868cb49e9.png)

Cmder on Windows:
![grafik](https://user-images.githubusercontent.com/33514570/61282897-77f8e000-a7bc-11e9-9ae9-1e06f2971d1b.png)

Maybe this helps

**Comment by jgirardet** [comment]
Is there something new about it ? Does someone tried wasabi with colorama on windows ?
